name: Nightly Prod-Template Refresh

on:
  workflow_dispatch:  # Allow manual trigger (and local testing with `act`)

jobs:
  refresh-prod-template:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4


      - name: Authenticate gcloud
        uses: google-github-actions/auth@v2
        with:
          # Uses the service account JSON from your GitHub secret (or from `act`).
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.10.1'  # or your preferred version
      
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      
      - name: Ensure pg-stress workspace
        working-directory: terraform
        run: |
          # Attempt to select pg-stress. If that fails, create it and select it.
          terraform workspace select pg-stress || \
            (terraform workspace new pg-stress && terraform workspace select pg-stress)

      - name: Terraform Plan
        working-directory: terraform 
        run: terraform plan
      
      - name: terraform apply
        working-directory: terraform
        if: false
        run: terraform apply -auto-approve
      
      - name: Terraform destroy
        working-directory: terraform
        if: true
        run: terraform destroy -auto-approve


